import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Card } from './Card'
import { Nav } from './Nav'
import data from "../data.json";

export default function Home() {
  const user = 'Jeremy Robson';
  const timeframes =[
    {title:'Daily'},
    {title:'Weekly'},
    {title:'Monthly'}
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav 
        timeframes={timeframes} 
        name={user}
        />
        <div className={styles.grid}>
        {data.map(item=>{
          console.log(item)
          return(
            <Card 
              category={item.title}
              current={item.timeframes.daily.current}
              previous={item.timeframes.daily.previous}
              />
          )})}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
