import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Card } from './Card'
import { Nav } from './Nav'
import data from "../data.json";
import { useState } from 'react'

export default function Home() {
  const user = 'Jeremy Robson';
  const [time,setTime] = useState([
    {id:1, title:'Daily',action:true},
    {id:2, title:'Weekly',action:false},
    {id:3, title:'Monthly',action:false}
  ])
  const [activeState,setActiveState] = useState(1)
  const onChange = index =>{
    setTime(
      time.map(item => 
          item.id === index 
          ? {...item, action : true} 
          : {...item, action : false} 
    ))
        setActiveState(index)
  }
  console.log(activeState)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav 
        timeframes={time} 
        onChange={onChange}
        name={user}
        />
        <div className={styles.grid}>
        {data.map(item=>{
          const current = (activeState==1)?item.timeframes.daily.current
          :(activeState==2)?item.timeframes.weekly.current
          :(activeState==3)?item.timeframes.monthly.current
          :null;

          const previous = (activeState==1)?item.timeframes.daily.previous
          :(activeState==2)?item.timeframes.weekly.previous
          :(activeState==3)?item.timeframes.monthly.previous
          :null;

          return(
            <Card 
              key={item.id}
              category={item.title}
              current={current}
              previous={previous}
              />
          )})}
        </div>
      </main>

      <footer className={styles.footer}>
        Code by&nbsp;
        <a className={styles.name} href="https://www.linkedin.com/in/laveezah-noor/">Laveezah Noor</a>.
        
      </footer>
    </div>
  )
}
